version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn global add swagger-cli
      - run: swagger-cli validate ./apis/validator/beacon-node-oapi.yaml
