get:
  operationId: getSpec
  summary: Get spec params.
  description: Retrieve specification configuration used on this node. [Specification params list](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml)
  tags:
    - Config
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                description: Key value mapping of [spec variables](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml)
                type: object
    "500":
      $ref: ../../beacon-node-oapi.yaml#/components/responses/InternalError