get:
  operationId: getSpec
  summary: Get spec params.
  description: |
    Retrieve specification configuration (without Phase 1 params) used on this node.
    [Specification params list](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml)

    Values are returned with following format:
      - any value starting with 0x in the spec is returned as a hex string
      - all other values are returned as number
  tags:
    - Config
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                description: |
                  Key value mapping of Phase 0[spec variables](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml).
                  Values are returned with following format:
                    - any value starting with 0x in the spec is returned as a hex string
                    - all other values are returned as number
                type: object
    "500":
      $ref: ../../beacon-node-oapi.yaml#/components/responses/InternalError